name: Build and Test Ollama with Open WebUI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start Docker Compose services
        run: |
          docker compose up -d
          sleep 30 # Wait for services to start

      - name: Test Ollama API
        run: |
          curl --fail http://localhost:11434 || exit 1

      - name: Test Open WebUI
        run: |
          curl --fail http://localhost:3000 || exit 1

      - name: Stop Docker Compose services
        run: |
          docker compose down